language: python
sudo: false
python:
    - "2.7"
    - "3.4"
    - "3.5"

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install dask numba numpy odo pandas pillow pytest toolz xarray
  # Need a few fixes to odo and datashape that aren't in the latest release
  - conda install -c blaze datashape
  - pip install --upgrade --no-deps git+https://github.com/Blaze/odo

  - python setup.py develop --no-deps

script:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then py.test datashader --doctest-modules --doctest-ignore-import-errors --verbose; else py.test datashader --verbose; fi

notifications:
  email: false
