name: ds
channels:
 - conda-forge
 - ioam/label/dev
 - ioam
 - scitools/label/dev

dependencies:
 - attrs
 - bokeh
 - cartopy
 - colorcet
 - dask
 - datashader
 - dill
 - distributed
 - geoviews
 - holoviews
 - iris
 - jupyter
 - krb5
 - matplotlib
 - networkx
 - numba
 - numpy
 - pandas
 - paramnb
 - pyproj
 - pytables
 - pytest
 - python=3.6
 - rasterio
 - requests
 - scipy
 - shapely
 - statsmodels
 - tblib
 - xarray
 - yaml
 - fastparquet
 - snappy
 - python-snappy
 - jupyter_dashboards 
 - pip:
   - cachey
